"""
Google Calendar Integration
Creates per-user Google Calendar events directly from the backend.
"""
from __future__ import annotations

from datetime import date, datetime, time, timedelta

from app.core.settings import settings

CALENDAR_SCOPE = "https://www.googleapis.com/auth/calendar.events"


class GoogleCalendarClient:
    """Thin wrapper around Google OAuth and Calendar API calls."""

    def build_authorization_url(self, state: str) -> str:
        flow = self._build_flow()
        authorization_url, _ = flow.authorization_url(
            access_type="offline",
            include_granted_scopes="true",
            prompt="consent",
            state=state,
        )
        return authorization_url

    def exchange_code_for_refresh_token(self, code: str) -> str:
        flow = self._build_flow()
        flow.fetch_token(code=code)
        refresh_token = flow.credentials.refresh_token
        if not refresh_token:
            raise RuntimeError("Google did not return a refresh token")
        return refresh_token

    def create_all_day_event(self, refresh_token: str, title: str, event_date: str, description: str = "") -> dict:
        start_date = date.fromisoformat(event_date)
        event = {
            "summary": title,
            "description": description or "Generated by Academix",
            "start": {"date": start_date.isoformat()},
            "end": {"date": (start_date + timedelta(days=1)).isoformat()},
        }
        return self._service(refresh_token).events().insert(calendarId="primary", body=event).execute()

    def create_timed_event(
        self,
        refresh_token: str,
        title: str,
        event_date: str,
        duration_hours: float,
        start_time: str = "09:00",
        description: str = "",
    ) -> dict:
        start = datetime.combine(date.fromisoformat(event_date), time.fromisoformat(start_time))
        end = start + timedelta(hours=duration_hours or 1)
        event = {
            "summary": title,
            "description": description or "Generated by Academix",
            "start": {"dateTime": start.isoformat(), "timeZone": settings.TIMEZONE},
            "end": {"dateTime": end.isoformat(), "timeZone": settings.TIMEZONE},
        }
        return self._service(refresh_token).events().insert(calendarId="primary", body=event).execute()

    def list_events(self, refresh_token: str, time_min: str, time_max: str, max_results: int = 50) -> list:
        """
        Fetch events from the user's primary Google Calendar within a date range.
        time_min / time_max: RFC3339 datetime strings e.g. '2026-06-01T00:00:00Z'
        """
        result = (
            self._service(refresh_token)
            .events()
            .list(
                calendarId="primary",
                timeMin=time_min,
                timeMax=time_max,
                maxResults=max_results,
                singleEvents=True,
                orderBy="startTime",
            )
            .execute()
        )
        items = result.get("items", [])
        events = []
        for item in items:
            start = item.get("start", {})
            end = item.get("end", {})
            events.append({
                "id": item.get("id"),
                "title": item.get("summary", "Untitled"),
                "description": item.get("description", ""),
                "date": start.get("date") or (start.get("dateTime") or "")[:10],
                "start_time": start.get("dateTime"),
                "end_time": end.get("dateTime"),
                "all_day": "date" in start,
                "type": "Google Calendar",
                "source": "google",
            })
        return events

    def get_free_busy(self, refresh_token: str, time_min: str, time_max: str) -> list[dict]:
        """
        Fetch Free/Busy information for the primary calendar.
        Returns a list of busy periods: [{"start": str, "end": str}]
        """
        body = {
            "timeMin": time_min,
            "timeMax": time_max,
            "items": [{"id": "primary"}]
        }
        result = self._service(refresh_token).freebusy().query(body=body).execute()
        return result.get("calendars", {}).get("primary", {}).get("busy", [])

    def _build_flow(self):
        from google_auth_oauthlib.flow import Flow

        if not settings.GOOGLE_CLIENT_ID or not settings.GOOGLE_CLIENT_SECRET or not settings.GOOGLE_REDIRECT_URI:
            raise RuntimeError("GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, and GOOGLE_REDIRECT_URI must be set")

        flow = Flow.from_client_config(
            {
                "web": {
                    "client_id": settings.GOOGLE_CLIENT_ID,
                    "client_secret": settings.GOOGLE_CLIENT_SECRET,
                    "auth_uri": "https://accounts.google.com/o/oauth2/auth",
                    "token_uri": "https://oauth2.googleapis.com/token",
                }
            },
            scopes=[CALENDAR_SCOPE],
        )
        flow.redirect_uri = settings.GOOGLE_REDIRECT_URI
        return flow

    def _service(self, refresh_token: str):
        from google.oauth2.credentials import Credentials
        from googleapiclient.discovery import build

        credentials = Credentials(
            token=None,
            refresh_token=refresh_token,
            token_uri="https://oauth2.googleapis.com/token",
            client_id=settings.GOOGLE_CLIENT_ID,
            client_secret=settings.GOOGLE_CLIENT_SECRET,
            scopes=[CALENDAR_SCOPE],
        )
        return build("calendar", "v3", credentials=credentials, cache_discovery=False)
