"""
Google Calendar Integration
Triggered via Make.com, not directly from backend.
This module holds the calendar payload builder only.
"""


class CalendarPayloadBuilder:

    def build_event_payload(self, event: dict) -> dict:
        """
        Build a Google Calendar API-compatible event payload.
        """
        # Note: Event is expected to be a dict representing ExtractedEvent and potentially times
        # For simplicity, we create an all-day event if time isn't specified.
        date_str = event.get("date")
        title = event.get("title", "CampusFlow Event")
        subject = event.get("subject")
        summary = f"[{subject}] {title}" if subject else title

        return {
            "summary": summary,
            "description": f"Generated by CampusFlow. Type: {event.get('type')}",
            "location": event.get("location", ""),
            "start": {
                "date": date_str
            },
            "end": {
                "date": date_str
            }
        }

