import logging
from typing import List
from app.repositories.user_repository import UserRepository
from app.integrations.calendar import GoogleCalendarClient
from app.schemas.tasks import TaskCreate
from app.schemas.intelligence import ExtractedEvent, ScheduleBlock

logger = logging.getLogger(__name__)

class CalendarSyncService:
    """
    Handles syncing extracted tasks and study schedules to Google Calendar.
    Designed to be run in background threads.
    """
    def __init__(self):
        self.user_repo = UserRepository()
        self.calendar_client = GoogleCalendarClient()

    def sync_events_background(self, user_id: str, events: List[ExtractedEvent]) -> None:
        """Syncs extracted events/tasks to Google Calendar."""
        profile = self.user_repo.get_automation_profile(user_id)
        if not profile:
            logger.info(f"Sync skipped: Profile not found for {user_id}")
            return
            
        refresh_token = profile.get("google_refresh_token")
        if not profile.get("google_calendar_connected") or not refresh_token:
            logger.info(f"Sync skipped: Google Calendar not connected for {user_id}")
            return
            
        for event in events:
            try:
                # If there's a specific date, we create an all-day event
                # In the future, we could add time extraction logic here too.
                if event.date and event.date != "unknown":
                    desc = f"Type: {event.type}"
                    if getattr(event, "subject", None):
                        desc += f"\nSubject: {event.subject}"
                    if getattr(event, "location", None):
                        desc += f"\nLocation: {event.location}"
                        
                    self.calendar_client.create_all_day_event(
                        refresh_token=refresh_token,
                        title=event.title,
                        event_date=event.date,
                        description=desc
                    )
            except Exception as e:
                logger.error(f"Failed to sync event {event.title} to calendar: {e}")

    def sync_schedules_background(self, user_id: str, schedules: List[ScheduleBlock]) -> None:
        """Syncs study schedule blocks to Google Calendar as timed events."""
        profile = self.user_repo.get_automation_profile(user_id)
        if not profile:
            logger.info(f"Sync skipped: Profile not found for {user_id}")
            return
            
        refresh_token = profile.get("google_refresh_token")
        if not profile.get("google_calendar_connected") or not refresh_token:
            logger.info(f"Sync skipped: Google Calendar not connected for {user_id}")
            return
            
        for block in schedules:
            try:
                if block.date and block.date != "unknown":
                    # Convert duration_minutes to hours for the timed_event function
                    duration_hours = block.duration_minutes / 60.0
                    
                    self.calendar_client.create_timed_event(
                        refresh_token=refresh_token,
                        title=f"Study: {block.focus_topic}",
                        event_date=block.date,
                        duration_hours=duration_hours,
                        # Defaulting start time to 09:00 if not specified, 
                        # future improvements could intelligently place these blocks.
                        start_time="09:00",
                        description=f"Generated by CampusFlow AI.\nSubject: {block.subject}"
                    )
            except Exception as e:
                logger.error(f"Failed to sync schedule block {block.focus_topic} to calendar: {e}")
